zookeeper:
  image: vungle/zookeeper
  ports: 
    - "2181"

kafka: 
  image: vungle/kafka
  ports:
    - "9092"
  links: 
    - zookeeper:zk
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

replay:
  image: vungle/replay
  links:
    - kafka:kafka
  restart: always
  volumes:
    - "./log:/var/log/"
  environment:
    KAFKA_TOPIC: "as-requestAds"
